gitlab-snowflake:
  outputs:
    dev:
      account: gitlab
      authenticator: externalbrowser
      database: CSHARP
      role: CSHARP
      schema: preparation
      threads: 8
      type: snowflake
      user: csharp@gitlab.com
      warehouse: DEV_XS
  target: dev
