version: 2

models:
  - name: rpt_available_to_renew_8th_calendar_day
    description: Snapshot of the daily available to renew model taken on the 8th calendar day after month-end close.

  - name: rpt_available_to_renew_45th_calendar_day
    description: Snapshot of the daily available to renew model taken on the 45th calendar day after month-end close.

  - name: rpt_available_to_renew_top_monthly_changes
    description: Report showing the subscriptions which moved into and out of available to renew status by month. Filtered to the top 10 subscriptions by ARR.
    columns:
      - name: first_day_of_month
        description: The first day of the month being compared
      - name: parent_crm_account_name
        description: '{{ doc("parent_crm_account_name") }}'
      - name: subscription_name
        description: Name applied to the subscription.
      - name: total_arr
        description: Annual recurring revenue associated with the subscription.
      - name: atr_change_flag
        description: ' {{ doc("atr_change_flag") }} '
      - name: renewal_month
      - name: fiscal_quarter_name_fy
      - name: dim_subscription_id
      - name: dim_crm_opportunity_id
      - name: product_tier_name
      - name: subscription_start_month
      - name: subscription_end_month
      - name: multi_year_booking_subscription_end_month
