version: 2

models:
  - name: omamori_entity_data_source
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: entity_id
      - name: entity_type
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null

  - name: omamori_mitigation_plan_entity_data_source
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: status
      - name: entity_datum_id
      - name: mitigation_plan_id
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null

  - name: omamori_mitigation_plans_source
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: entity_type
      - name: priority
      - name: status
      - name: feature
      - name: category
      - name: last_applied_mitigation_plan_template_id
      - name: from_rule_evaluation_id
      - name: created_at
        tests:
          - not_null
      - name: created_by_id
      - name: reviewed_at
      - name: reviewed_by_id
      - name: executed_at
      - name: executed_by_id
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null

  - name: omamori_rule_evaluation_matches_source
    columns:
      - name: id
      - name: entity_dataum_id
      - name: rule_evaluation_id
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null

  - name: omamori_rule_evaluations_source
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: rule
      - name: result
      - name: elapsed_ms
      - name: throttled_count
      - name: duplicates_removed
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null

  - name: omamori_tags_source
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null

  - name: omamori_users_source
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: username
      - name: name
      - name: role
      - name: service_user
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at
        tests:
          - not_null
