version: 2

models:
  - name: omamori_entity_data_source
    description: entity_data from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: entity_id
      - name: entity_type
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        tests:
          - not_null
