version: 2

models:
  - name: omamori_entity_data_source
    description: entity_data from the GitLab Omamori application
    columns:
      - name: id
        description: The internal Omamori ID for the entity datum
        tests:
          - unique
          - not_null
      - name: entity_id
        description: The external ID of the entity datum
      - name: entity_type
        description: The type of entity datum
      - name: created_at
        description: When the entity datum was first imported to Omamori
        tests:
          - not_null
      - name: updated_at
        description: When the entity datum was last synchronized
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null

  - name: omamori_mitigation_plan_entity_data_source
    description: mitigation_plan_entity_data from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: status
      - name: entity_datum_id
      - name: mitigation_plan_id
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null

  - name: omamori_mitigation_plan_tags_source
    description: mitigation_plan_tags from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: mitigation_plan_id
      - name: tag_id

  - name: omamori_mitigation_plan_template_tags_source
    description: mitigation_plan_template_tags from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: mitigation_plan_template_id
      - name: tag_id

  - name: omamori_mitigation_plans_source
    description: mitigation_plans from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: entity_type
      - name: priority
      - name: status
      - name: feature
      - name: category
      - name: last_applied_mitigation_plan_template_id
      - name: from_rule_evaluation_id
      - name: created_at
        tests:
          - not_null
      - name: created_by_id
      - name: reviewed_at
      - name: reviewed_by_id
      - name: executed_at
      - name: executed_by_id
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null

  - name: omamori_rule_evaluation_matches_source
    description: rule_evaluation_matches from the GitLab Omamori application
    columns:
      - name: id
      - name: entity_dataum_id
      - name: rule_evaluation_id
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null

  - name: omamori_rule_evaluations_source
    description: rule_evaluations from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: rule
      - name: outcome
      - name: elapsed_ms
      - name: throttled_count
      - name: duplicates_removed
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null

  - name: omamori_tags_source
    description: tags from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: tag_name
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null

  - name: omamori_users_source
    description: users from the GitLab Omamori application
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: username
      - name: full_name
      - name: user_role
      - name: service_user
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: uploaded_at_gcs
        description: Datetime that source parquet file was uploaded to GCS
        tests:
          - not_null
