# ======
# CI Stages
# ======
stages:
  - base
  - Python

job_name:
  stage: base
  script:
    - echo "Hello, GitLab CI!"
  only:
    refs:
      - merge_requests
  when: always

snowflake_provisioning_snowflake_users:
  stage: Python
  rules:
    # only allow trigger if MR approved
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_APPROVED == "true"'
      when: manual
  script:
    - echo "hello users"

snowflake_provisioning_roles_yaml:
  stage: Python
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  script:
    - echo "hello roles"
