# ======
# CI Stages
# ======
stages:
  - Python

requires_approval_job:
  stage: Python
  rules:
    # only allow trigger if MR approved
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_APPROVED == "true"'
      when: manual
  script:
    - echo "The MR should have been approved"

no_requires_approval_job:
  stage: Python
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  script:
    - echo "MR approval not required"
