version: 2

models:
  - name: wk_employees
    columns:
      - name: employee_number
        tests:
          - not_null
      - name: employee_id
      - name: first_name
      - name: last_name
      - name: hire_date
      - name: termination_date
      - name: first_inactive_date
      - name: age_cohort
      - name: gender
      - name: gender_identity
      - name: ethnicity
      - name: country
      - name: nationality
      - name: region
      - name: region_modified
      - name: gender_region
      - name: greenhouse_candidate_id
      - name: last_updated_date
      - name: urg_group
      - name: last_work_email
      - name: gitlab_username
      - name: date_of_birth
  - name: wk_department
    columns:
      - name: division
      - name: modified_division
      - name: cost_center
      - name: department
      - name: modified_department
      - name: is_quota_carrying
      - name: is_active
      - name: last_updated
  - name: wk_job_history
    columns: 
      - name: employee_id
        tests:
          - not_null
      - name: full_name
      - name: employment_status
      - name: min_date
      - name: max_date
      - name: job_change_reason
      - name: country
      - name: region
      - name: location_factor
      - name: cost_center
      - name: division
      - name: department
      - name: job_role
      - name: job_grade
      - name: job_title
      - name: jobtitle_speciality
      - name: employee_type
      - name: reports_to
      - name: reports_to_id
      - name: total_direct_reports
      - name: hire_date
      - name: hire_rank
      - name: last_date
      - name: termination_date
      - name: term_rank
      - name: termination_type
      - name: termination_reason
      - name: exit_impact
      - name: job_start_date
      - name: job_end_date
      - name: discretionary_bonus_count
  - name: wk_talent_flow
    columns: 
      - name: employee_id
      - name: full_name
      - name: employment_status
      - name: min_date
      - name: max_date
      - name: job_change_reason
      - name: country
      - name: region
      - name: cost_center
      - name: division
      - name: department
      - name: job_title
      - name: job_role
      - name: reports_to
      - name: hire_date
      - name: hire_rank
      - name: last_date
      - name: termination_date
      - name: term_rank
      - name: termination_type
      - name: termination_reason
      - name: exit_impact
      - name: termination_initiated_at
      - name: employee_type
      - name: discretionary_bonus_count