version: 2

models:
  - name: wk_employees
    columns:
      - name: employee_number
        tests:
          - not_null
      - name: employee_id
      - name: first_name
      - name: last_name
      - name: hire_date
      - name: termination_date
      - name: first_inactive_date
      - name: age_cohort
      - name: gender
      - name: gender_identity
      - name: ethnicity
      - name: country
      - name: nationality
      - name: region
      - name: region_modified
      - name: gender_region
      - name: greenhouse_candidate_id
      - name: last_updated_date
      - name: urg_group
      - name: last_work_email
      - name: gitlab_username
      - name: date_of_birth
  - name: wk_department
    columns:
      - name: division
      - name: modified_division
      - name: cost_center
      - name: department
      - name: modified_department
      - name: is_quota_carrying
      - name: is_active
      - name: last_updated
  - name: wk_job_history
    columns: 
      - name: employee_id
        tests:
          - not_null
      - name: full_name
      - name: employment_status
      - name: min_date
      - name: max_date
      - name: job_change_reason
      - name: country
      - name: region
      - name: location_factor
      - name: cost_center
      - name: division
      - name: department
      - name: job_role
      - name: job_grade
      - name: job_title
      - name: jobtitle_speciality
      - name: employee_type
      - name: reports_to
      - name: reports_to_id
      - name: total_direct_reports
      - name: hire_date
      - name: hire_rank
      - name: last_date
      - name: termination_date
      - name: term_rank
      - name: termination_type
      - name: termination_reason
      - name: exit_impact
      - name: job_start_date
      - name: job_end_date
      - name: discretionary_bonus_count
  - name: wk_talent_flow
    columns: 
      - name: employee_id
      - name: full_name
      - name: employment_status
      - name: min_date
      - name: max_date
      - name: job_change_reason
      - name: country
      - name: region
      - name: cost_center
      - name: division
      - name: department
      - name: job_title
      - name: job_role
      - name: reports_to
      - name: hire_date
      - name: hire_rank
      - name: last_date
      - name: termination_date
      - name: term_rank
      - name: termination_type
      - name: termination_reason
      - name: exit_impact
      - name: termination_initiated_at
      - name: employee_type
      - name: discretionary_bonus_count
  - name: wk_pto
    columns: 
      - name: employee_id
      - name: hire_date
      - name: term_date
      - name: last_date
      - name: date_actual
      - name: is_pto_date
      - name: is_pto_full_day
      - name: is_pto_holiday
      - name: running_pto_sum
      - name: running_pto_sum_mtd
      - name: running_pto_sum_qtd
      - name: running_pto_sum_ytd
      - name: running_pto_sum_r12
  - name: wk_talent_acquisition
    columns: 
      - name: id
      - name: job_id
      - name: job_opening_id
      - name: candidate_id
      - name: application_id
      - name: offer_id
      - name: start_datetime
      - name: end_datetime
      - name: start_date
      - name: end_date
      - name: id
      - name: status
      - name: status_id
      - name: max_start_date
      - name: max_end_date
      - name: min_start_date
      - name: is_max_record
      - name: is_max_hire_progress_step
  - name: wk_talent_acquisition_application
    columns: 
      - name: application_id
      - name: candidate_id
      - name: job_id
      - name: job_post_id
      - name: applied_at
      - name: application_status
      - name: source_name
      - name: source_type
      - name: prospect
      - name: sourcer_name
      - name: referrer_name
      - name: referrer_employee_id
      - name: rejected_by
      - name: rejected_by_employee_id
      - name: rejection_reason_name
      - name: rejection_reason_type
      - name: rejected_at
      - name: hired_at
      - name: started_at
      - name: external_start
      - name: created_at
      - name: last_updated_at
  - name: wk_talent_acquisition_candidate
    columns: 
      - name: candidate_id
      - name: candidate_recruiter_id
      - name: candidate_coordinator_id
      - name: candidate_recruiter
      - name: recruiter_id
      - name: coordinator_id
      - name: canddidate_coordinator
      - name: candidate_company
      - name: candidate_title
      - name: candidate_created_at
      - name: candidate_updated_at
      - name: is_candidate_migrated
      - name: is_candidate_private
      - name: first_name
      - name: last_name
      - name: country
      - name: locality
      - name: relationship
      - name: family_relationship
      - name: referral
      - name: preferred_first
      - name: referral_notes