version: 2

models:
  - name: wk_sales_clari_net_arr_forecast
    description: Forecast table combining the different API sub-payloads together
    columns:
      - name: user_full_name
        tests:
          - not_null
      - name: user_email
        tests:
          - not_null
      - name: crm_user_id
        tests:
          - not_null
      - name: sales_team_role
        tests:
          - not_null
      - name: parent_role
      - name: fiscal_quarter
        tests:
          - not_null
      - name: field_name
        tests:
          - not_null
      - name: week_number
        tests:
          - not_null
      - name: week_start_date
        tests:
          - not_null
      - name: week_end_date
        tests:
          - not_null
      - name: field_type
        tests:
          - not_null
      - name: forecast_value
      - name: is_updated
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - fiscal_quarter
            - week_start_date 
            - crm_user_id
            - field_name
  - name: wk_prep_sales_funnel_target
    description: Prep model for SSOT sales funnel targets
    columns:
      - name: dim_crm_user_hierarchy_sk
        tests:
          - not_null
  - name: wk_fct_sales_funnel_target
    description: Prep model for SSOT sales funnel targets
    columns:
      - name: kpi_name
        tests:
          - not_null
        tags: ["tdf", "common", "sales_funnel"]
      - name: sales_funnel_target_id
        tests:
          - not_null
          - unique
        tags: ["tdf", "common", "sales_funnel"]
      - name: dim_sales_funnel_kpi_sk
        tests:
          - not_null
        tags: ["tdf", "common", "sales_funnel"]
  - name: wk_prep_sales_funnel_kpi
    description: Prep model for SSOT sales funnel targets
    columns:
      - name: dim_sales_funnel_kpi_sk
        tests:
          - not_null
          - unique
      - name: sales_funnel_kpi_name
        tests:
          - not_null
  - name: wk_prep_crm_user_hierarchy
    description: Prep model for SSOT sales funnel targets
    columns:
      - name: dim_crm_user_hierarchy_id
        description: Unique identifier of a sales hierarchy tier
        tests:
          - not_null
          - unique
  - name: wk_mart_sales_funnel_target
    description: Model with Sales targets used for planning the go to market Sales and Marketing motion.
    columns:
      - name: sales_funnel_target_id
        tests:
            - not_null
            - unique
        tags: ["tdf", "mart", "sales_funnel"]
  - name: wk_dim_crm_user_hierarchy
    columns:
      - name: dim_crm_user_hierarchy_id
        tests:
          - not_null
          - unique
        tags: ["tdf", "common", "sales_funnel"]
  - name: wk_dim_sales_funnel_kpi
    columns:
      - name: dim_sales_funnel_kpi_sk
        tests:
          - not_null
  - name: wk_fct_sales_funnel_target_daily
    columns:
      - name: kpi_name
        tests:
          - not_null
        tags: ["tdf", "common", "sales_funnel"]
      - name: sales_funnel_target_daily_pk
        tests:
          - not_null
          - unique
        tags: ["tdf", "common", "sales_funnel"]
      - name: dim_sales_funnel_kpi_sk
        tests:
          - not_null
  - name: wk_rpt_crm_opportunity_reduced
    description: a table with reduced column list from mart_crm_opportunity that is used for testing entitlement tables for Tableau
    columns:
      - name: dim_crm_opportunity_id
        tests:
            - not_null
            - unique
  - name: wk_rpt_crm_account_reduced
    description: a table with reduced column list from mart_crm_account that is used for testing entitlement tables for Tableau
    columns:
      - name: dim_crm_account_id
        tests:
            - not_null
            - unique
  - name: wk_prep_crm_account_share_active
    description: an active account share table with reduced column list
    columns:
      - name: account_id
        tests:
            - not_null
            - unique
  - name: wk_prep_crm_opportunity_share_active
    description: an active opportunity share table with reduced column list
    columns:
      - name: opportunity_id
        tests:
            - not_null
            - unique
  - name: wk_account_entitlement_table
    description: an entitlment table to be used for row level security in Tableau
    columns:
      - name: account_id