version: 2
models:
  - name: adaptive_accounts_source
    description: Adaptive account info
    columns:
      - name: id
        tests:
          - not_null
  - name: adaptive_attributes_source
    description: Adaptive attributes info
    columns:
      - name: parent_id
        tests:
          - not_null
  - name: adaptive_dimension_families_source
    description: Adaptive dimension family info
    columns:
      - name: id
        tests:
          - not_null
  - name: adaptive_dimension_mapping_source
    description: Adaptive dimension mapping info 
    columns:
      - name: version_id
        tests:
          - not_null
      - name: dimension_id
        tests:
          - not_null
  - name: adaptive_dimensions_source
    description: Adaptive dimension info 
    columns:
      - name: parent_id
        tests:
          - not_null
  - name: adaptive_instances_source
    description: Adaptive instance info 
    columns:
      - name: instance_name
        tests:
          - not_null
  - name: adaptive_users_source
    description: Adaptive users info
    columns:
      - name: id
        tests:
          - not_null
  - name: adaptive_versions_source
    description: Adaptive version info 
    columns:
      - name: parent_id
        tests:
          - not_null
