
version: 2

sources:
  - name: gitlab_dotcom_merge_request_diff_commits
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_postgres
    loader: Airflow
    loaded_at_field: DATEADD(sec, _uploaded_at, '1970-01-01')

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: merge_request_diff_commits
        identifier: gitlab_db_merge_request_diff_commits
