version: 2

models:

  - name: zuora_central_sandbox_charge_metrics_source
    description: Source layer for Zuora charge metrics from sandbox environment
    columns:
      - name: charge_metrics_id
        tags: [ "tdf", "zuora", "zuora_query_api" ]
        data_tests:
          - not_null
          - unique