version: 2

models:

  - name: customers_db_reconciliations
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_dast_profiles
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_users_security_dashboard_projects
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_approval_project_rules_users
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_fork_network_members
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_pages_domains
    description: Workspace model of the source data (deduplicated).
    
  - name: gitlab_dotcom_project_ci_cd_settings
    description: Workspace model of the source data (deduplicated).
    
  - name: gitlab_dotcom_project_features
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_project_settings
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_protected_branch_merge_access_levels
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_protected_branch_push_access_levels
    description: Workspace model of the source data (deduplicated).

  - name: gitlab_dotcom_resource_iteration_events
    description: Workspace model of the source data (deduplicated).

  - name: version_usage_ping_errors
    description: Workspace model of the source data (one to one copy).

  - name: version_usage_ping_metadata
    description: Workspace model of the source data (one to one copy).

  - name: gitlab_dotcom_ml_candidates
    description: Workspace model of the GitLab.com ml_candidates table (deduplicated).
    columns:
      - name: ml_candidate_id
        description: Appears as `id` in the source data
      - name: created_at
      - name: updated_at
      - name: experiment_id
      - name: user_id
        description: The unique identifier (and natural key) of the user, easily joined to `dim_user`.
      - name: start_at
        description: Appears as `start_time` in the source data
      - name: end_at
        description: Appears as `end_time` in the source data
      - name: status

  - name: gitlab_dotcom_ml_experiments
    description: Workspace model of the GitLab.com ml_experiments table (deduplicated).
    columns:
      - name: ml_experiment_id
        description: Appears as `id` in the source data
      - name: created_at
      - name: updated_at
      - name: ml_experiment_iid
        description: Appears as `iid` in the source data
      - name: project_id
        description: '{{ doc("dim_project_id") }}'
      - name: user_id
        description: The unique identifier (and natural key) of the user, easily joined to `dim_user`.
      - name: deleted_on
