version: 2

models:
    - name: google_analytics_4_events_source
      columns:
        - name: date_part
          tests:
            - not_null
    - name: google_analytics_4_pseudonymous_users_source
      columns:
        - name: pseudo_user_id
          tests:
            - not_null
        - name: date_part
          tests:
            - not_null
    - name: google_analytics_4_user_audiences_source
      columns:
        - name: date_part
          tests:
            - not_null
