version: 2

models:
    - name: thanos_stage_group_error_budget_availability_source
      columns:
        - name: metric_product_stage
          tests:
              - not_null
        - name: metric_stage_group
          tests:
              - not_null
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_stage_group_error_budget_seconds_spent_source
      columns:
        - name: metric_product_stage
          tests:
              - not_null
        - name: metric_stage_group
          tests:
              - not_null
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_stage_group_error_budget_seconds_remaining_source
      columns:
        - name: metric_product_stage
          tests:
              - not_null
        - name: metric_stage_group
          tests:
              - not_null
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_total_haproxy_bytes_out
      columns:
        - name: metric_backend
        - name: metric_created_at
        - name: metric_value
          tests:
              - not_null
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_stage_group_error_budget_completeness_source
      columns:
        - name: metric_time_stamp
        - name: metric_value
          tests:
              - not_null
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
    - name: thanos_daily_slas_source
      columns:
        - name: metric_query
        - name: metric_env
        - name: metric_environment
        - name: metric_monitor
        - name: metric_ruler_cluster
        - name: metric_sla_type
        - name: metric_stage
        - name: metric_created_at
        - name: metric_value
        - name: result_type
        - name: status_type
        - name: message_type
        - name: status_code
        - name: is_success
