version: 2

models:
  - name: customers_db_leads
    description: This model is the data from tap-postgres for the leads table from customers.gitlab.com. The schema of the database is defined in [this ruby code](https://gitlab.com/gitlab-org/customers-gitlab-com/blob/master/db/schema.rb).    

