[tool.poetry]
name = "analytics"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8.0"
dbt-snowflake = "1.2.0"
dbt-core= "1.2.3"
gitlabdata = "0.3.13"
loguru = "0.6.0"
pandas = "1.4.2"
requests = "2.27.1"
SQLAlchemy = "1.4.46"
sqlfluff = "1.4.5"
sqlfluff-templater-dbt = "1.4.5"
simple-dependency-resolver = "0.1.1"

