version: 2

models:
  - name: sfdc_pipeline_waterfall
    description: Model to describe pipeline movement from the first day of the quarter to the first day of the following quarter.
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
