version: 2

models:
  - name: rpt_delta_arr_parent_month_8th_calendar_day
    description: '{{ doc("rpt_delta_arr_parent_month_8th_calendar_day") }}'

  - name: rpt_delta_arr_parent_product_month_8th_calendar_day
    description: '{{ doc("rpt_delta_arr_parent_product_month_8th_calendar_day") }}'

  - name: rpt_crm_opportunity_snapshot_8th_calendar_day
    description: Snapshot of mart_crm_opportunity_daily_snapshot taken on the 8th calendar day after month-end close.
    columns:
      - name: crm_opportunity_snapshot_id
        data_tests:
          - not_null
          - unique
    
  - name: rpt_crm_opportunity_renewal
    description: '{{ doc("rpt_crm_opportunity_renewal") }}'

  - name: rpt_crm_opportunity_open
    description: '{{ doc("rpt_crm_opportunity_open") }}'

  - name: rpt_stage_progression
    description: '{{ doc("rpt_stage_progression") }}' 
    columns: 
      - name: dim_crm_opportunity_id
        data_tests:
          - not_null
          - unique
