version: 2

models:
  - name: rpt_delta_arr_parent_month_8th_calendar_day
    description: '{{ doc("rpt_delta_arr_parent_month_8th_calendar_day") }}'

  - name: rpt_delta_arr_parent_product_month_8th_calendar_day
    description: '{{ doc("rpt_delta_arr_parent_product_month_8th_calendar_day") }}'

  - name: rpt_crm_opportunity_snapshot_8th_calendar_day
    description: Snapshot of mart_crm_opportunity_daily_snapshot taken on the 8th calendar day after month-end close.
    columns:
      - name: crm_opportunity_snapshot_id
        tests:
          - not_null
          - unique

  - name: rpt_retention_parent_account
    description: Report table to support retention analysis at the ultimate_parent_account. This models is built on top of rpt_delta_arr_parent_month_8th_calendar_day.
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique

  - name: rpt_retention_parent_account_product
    description: Report table to support retention analysis at the ultimate_parent_account || product level. This models is built on top of rpt_delta_arr_parent_month_8th_calendar_day.
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique

  - name: rpt_retention_parent_account_delivery_type
    description: Report table to support retention analysis at the ultimate_parent_account || delivery_type. This models is built on top of rpt_delta_arr_parent_month_8th_calendar_day.
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
