version: 2

models:

  - name: fct_behavior_link_click
    description: A derived fact from fct_behavior_unstructured_event containing only link_click event types.
    columns: 
      - name: fct_behavior_unstructured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_service_ping_context
    description: Derived fact table that parses out the Redis event from the Service Ping context which can optionally be sent with an event.
    columns:
      - name: behavior_structured_event_pk
        tests:
        - unique:
            config:
              where: "behavior_at >= DATEADD('day',-3,CURRENT_DATE())"
        - not_null

  - name: wk_fct_behavior_structured_event_ide_extension_version
    description: Derived fact table that parses out the [ide_extension_version context](https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/issues/256#contexts) based on the [schema](https://gitlab.com/gitlab-org/iglu/-/tree/master/public/schemas/com.gitlab/ide_extension_version/jsonschema) which can optionally be sent with an event.
    columns:
      - name: behavior_structured_event_pk
        description: '{{ doc("behavior_structured_event_pk") }}'
        tests:
        - unique:
            config:
              where: "behavior_at >= DATEADD('day',-3,CURRENT_DATE())"
        - not_null
      - name: behavior_at
        description: ' {{ doc("behavior_at") }}'
      - name: ide_extension_version_context
        description: '{{ doc("ide_extension_version_context") }}'
      - name: extension_name
        description: '{{ doc("ide_extension_name") }}'
      - name: extension_version
        description: '{{ doc("ide_extension_version") }}'
      - name: ide_name
        description: '{{ doc("ide_extension_ide_name") }}'
      - name: ide_vendor
        description: '{{ doc("ide_extension_ide_vendor") }}'
      - name: ide_version
        description: '{{ doc("ide_extension_ide_version") }}'
      - name: language_server_version
        description: '{{ doc("ide_extension_language_server_version") }}'

  - name: fct_behavior_structured_event_code_suggestions_context
    description: Derived fact table that parses out the code_suggestions_context context based on the [schema](https://gitlab.com/gitlab-org/iglu/-/tree/master/public/schemas/com.gitlab/code_suggestions_context/jsonschema) which can optionally be sent with an event.
    columns:
      - name: behavior_structured_event_pk
        description: '{{ doc("behavior_structured_event_pk") }}'
        tests:
        - unique:
            config:
              where: "behavior_at >= DATEADD('day',-3,CURRENT_DATE())"
        - not_null
      - name: behavior_at
        description: '{{ doc("behavior_at") }}'
      - name: code_suggestions_context
        description: '{{ doc("code_suggestions_context") }}'
      - name: model_engine
        description: '{{ doc("code_suggestions_model_engine") }}'
      - name: model_name
        description: '{{ doc("code_suggestions_model_name") }}'
      - name: prefix_length
        description: '{{ doc("code_suggestions_prefix_length") }}'
      - name: suffix_length
        description: '{{ doc("code_suggestions_suffix_length") }}'
      - name: language
        description: '{{ doc("code_suggestions_language") }}'
      - name: user_agent
        description: '{{ doc("code_suggestions_user_agent") }}'
      - name: delivery_type
        description: ' {{ doc("product_delivery_type") }} In the raw Snowplow data, this field comes through as `gitlab_realm`.'
        tests:
            - accepted_values:
                values: ['Self-Managed', 'SaaS']
      - name: api_status_code
        description: '{{ doc("code_suggestions_api_status_code") }}'
      - name: namespace_ids
        description: List of the namespace IDs that the user has a Code Suggestions subscription in SaaS for
      - name: ultimate_parent_namespace_ids
        description: List of ultimate parents namespace IDs that the namespaces_ids map to
      - name: subscription_names
        description: The most recent subscription associated with the namespace(s) associated with the Code Suggestion event, either through Orders for SaaS or through Service Ping for Self-Managed.
      - name: dim_crm_account_ids
        description: List of CRM account IDs that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: dim_parent_crm_account_ids
        description: List of ultimate parent CRM account IDs that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: dim_crm_account_id
        description: If a Code Suggestion has only one CRM account associated with it, we display the unique identifier for that CRM account. Otherwise, this field is NULL.
      - name: dim_parent_crm_account_id
        description: If a Code Suggestion has only one ultimate parent CRM account associated with it, we display the unique identifier for that ultimate parent CRM account. Otherwise, this field is NULL.
      - name: subscription_name
        description: If a Code Suggestion has only one subscription name associated with it, we display it. Otherwise, this field is NULL.
      - name: ultimate_parent_namespace_id
        description: If a Code Suggestion has only one ultimate parent namespace associated with it, we display the unique identifier for that ultimate parent namespace. Otherwise, this field is NULL.
      - name: dim_installation_id
        description: If a Code Suggestion has only one installation associated with it, we display the unique identifier for that installation. Otherwise, this field is NULL.
      - name: crm_account_names
        description: List of CRM account names that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: parent_crm_account_names
        description: List of ultimate parent CRM account names that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: crm_account_name
        description: If a Code Suggestion has only one CRM account associated with it, we display the account name for that CRM account. Otherwise, this field is NULL.
      - name: parent_crm_account_name
        description: If a Code Suggestion has only one ultimate parent CRM account associated with it, we display the account name for that ultimate parent CRM account. Otherwise, this field is NULL.
      - name: dim_installation_ids
        description: List of installations that are associated with a Code Suggestion through the `instance_id` listed in the event.
      - name: host_names
        description: List of host names that are associated with the a Code Suggestion through the `instance_id` listed in the event.
      - name: installation_host_name
        description:  If a Code Suggestion has only one host name associated with it, we display the unique identifier for that installation. Otherwise, this field is NULL.

  - name: wk_mart_behavior_structured_event_code_suggestion
    description: '{{ doc("wk_mart_behavior_structured_event_code_suggestion") }}'
    columns:
      - name: behavior_structured_event_pk
        description: '{{ doc("behavior_structured_event_pk") }}'
        tests:
        - unique:
            config:
              where: "behavior_at >= DATEADD('day',-3,CURRENT_DATE())"
        - not_null
      - name: behavior_at
        description: '{{ doc("behavior_at") }}'
      - name: behavior_date
        description: '{{ doc("behavior_date") }}'
      - name: app_id
        description: '{{ doc("app_id") }}'
      - name: event_action
        description: '{{ doc("event_action") }}'
      - name: event_category
        description: '{{ doc("event_category") }}'
      - name: event_property
        description: '{{ doc("event_property") }}'
      - name: event_label
        description: '{{ doc("event_label") }} On Code Suggestions events, this field is the unique identifier for the suggestion and can be used to join across events. This suggestion identifier is present on events from `app_id = gitlab_ide_extension`, but not `app_id = gitlab_ai_gateway`.'
      - name: language
        description: '{{ doc("code_suggestions_language") }}'
      - name: delivery_type
        description: ' {{ doc("product_delivery_type") }} In the raw Snowplow data, this field comes through as `gitlab_realm`. Appears in the `code_suggestions_context`.'
        tests:
            - accepted_values:
                values: ['Self-Managed', 'SaaS']
      - name: model_engine
        description: '{{ doc("code_suggestions_model_engine") }}'
      - name: model_name
        description: '{{ doc("code_suggestions_model_name") }}'
      - name: prefix_length
        description: '{{ doc("code_suggestions_prefix_length") }}'
      - name: suffix_length
        description: '{{ doc("code_suggestions_suffix_length") }}'
      - name: user_agent
        description: '{{ doc("code_suggestions_user_agent") }}'
      - name: api_status_code
        description: '{{ doc("code_suggestions_api_status_code") }}'
      - name: extension_name
        description: '{{ doc("ide_extension_name") }}'
      - name: extension_version
        description: '{{ doc("ide_extension_version") }}'
      - name: ide_name
        description: '{{ doc("ide_extension_ide_name") }}'
      - name: ide_vendor
        description: '{{ doc("ide_extension_ide_vendor") }}'
      - name: ide_version
        description: '{{ doc("ide_extension_ide_version") }}'
      - name: language_server_version
        description: '{{ doc("ide_extension_language_server_version") }}'
      - name: contexts
        description: '{{ doc("contexts") }}'
      - name: code_suggestions_context
        description: '{{ doc("code_suggestions_context") }}'
      - name: ide_extension_version_context
        description: '{{ doc("ide_extension_version_context") }}'
      - name: has_code_suggestions_context
        description: '{{ doc("has_code_suggestions_context") }}'
      - name: has_ide_extension_version_context
        description: '{{ doc("has_ide_extension_version_context") }}'
      - name: created_by
        description: '{{ doc("created_by") }}'
      - name: updated_by
        description: '{{ doc("updated_by") }}'
      - name: model_created_date
        description: '{{ doc("model_created_date") }}'
      - name: model_updated_date
        description: '{{ doc("model_updated_date") }}'
      - name: namespace_ids
        description: List of the namespace IDs that the user has a Code Suggestions subscription in SaaS for
      - name: ultimate_parent_namespace_ids
        description: List of ultimate parents namespace IDs that the namespaces_ids map to
      - name: subscription_names
        description: The most recent subscription associated with the namespace(s) associated with the Code Suggestion event, either through Orders for SaaS or through Service Ping for Self-Managed.
      - name: dim_crm_account_ids
        description: List of CRM account IDs that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: dim_parent_crm_account_ids
        description: List of ultimate parent CRM account IDs that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: dim_crm_account_id
        description: If a Code Suggestion has only one CRM account associated with it, we display the unique identifier for that CRM account. Otherwise, this field is NULL.
      - name: dim_parent_crm_account_id
        description: If a Code Suggestion has only one ultimate parent CRM account associated with it, we display the unique identifier for that ultimate parent CRM account. Otherwise, this field is NULL.
      - name: subscription_name
        description: If a Code Suggestion has only one subscription name associated with it, we display it. Otherwise, this field is NULL.
      - name: ultimate_parent_namespace_id
        description: If a Code Suggestion has only one ultimate parent namespace associated with it, we display the unique identifier for that ultimate parent namespace. Otherwise, this field is NULL.
      - name: dim_installation_id
        description: If a Code Suggestion has only one installation associated with it, we display the unique identifier for that installation. Otherwise, this field is NULL.
      - name: crm_account_names
        description: List of CRM account names that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: parent_crm_account_names
        description: List of ultimate parent CRM account names that are associated with the most recent paid subscriptions associated with the Code Suggestion event
      - name: crm_account_name
        description: If a Code Suggestion has only one CRM account associated with it, we display the account name for that CRM account. Otherwise, this field is NULL.
      - name: parent_crm_account_name
        description: If a Code Suggestion has only one ultimate parent CRM account associated with it, we display the account name for that ultimate parent CRM account. Otherwise, this field is NULL.
      - name: dim_installation_ids
        description: List of installations that are associated with a Code Suggestion through the `instance_id` listed in the event.
      - name: host_names
        description: List of host names that are associated with the a Code Suggestion through the `instance_id` listed in the event.
      - name: installation_host_name
        description:  If a Code Suggestion has only one host name associated with it, we display the unique identifier for that installation. Otherwise, this field is NULL.
