version: 2

models:
  - name: rpt_user_request_crm_account_issue_epic
    description: Aggregation of mart_user_request, which is at the issue/epic||link grain at the issue/epic||crm_account grain.
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
  - name: rpt_user_request_issue_epic
    description: Aggregation of mart_user_request at the issue/epic grain.
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
  - name: rpt_product_usage_health_score_account_roll_up
    description: This table calculates Account level scores for % of ARR reporting usage data, license utilization, User Engagement, SCM adoption, CI adoption, CD adoption, and Security Adoption. Those scores are then joined back to rpt_product_usage_health_score so that we maintain an instance-level grain for reporting in Customer Intelligence dashboards in Tableau. 
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - arr_month
            - mart_arr_all_account_id
            - primary_key