version: 2

models:
  - name: rpt_user_request_crm_account_issue_epic
    description: Aggregation of mart_user_request, which is at the issue/epic||link grain at the issue/epic||crm_account grain.
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
  - name: rpt_user_request_issue_epic
    description: Aggregation of mart_user_request at the issue/epic grain.
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
  - name: rpt_product_usage_health_score_with_arr
    description: Joined table between rpt_product_usage_health_score and mart_arr_all to calculate instance attributed ARR. This model powers Account Landscape dashboard in Tableau
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
