version: 2

models:
  - name: zuora_query_api_users_source
    description: Source layer for Zuora Users
    columns:
      - name: zuora_user_id
        tags: ["tdf", "zuora", "zuora_query_api"]
        tests:
          - not_null
          - unique

  - name: zuora_query_api_order_action_rate_plan_source
    description: Source layer for Zuora Order Action Rate Plan
    columns:
      - name: order_action_rate_plan_id
        tags: ["tdf", "zuora", "zuora_query_api"]
        tests:
          - not_null
          - unique