connection_info:
  postgres_source_connection:
    database: GITLAB_COM_DB_NAME
    host: GITLAB_COM_DB_HOST
    pass: GITLAB_COM_DB_PASS
    port: GITLAB_COM_SCD_PG_PORT
    user: GITLAB_COM_DB_USER
tables:
