connection_info:
  postgres_source_connection:
    database: CUSTOMERS_DB_NAME
    host: CUSTOMERS_DB_HOST
    pass: CUSTOMERS_DB_PASS
    port: PG_PORT
    user: CUSTOMERS_DB_USER
tables:
  billing_accounts:
    advanced_metadata: true
    export_db: EXPORT_DB
    export_schema: 'customers'
    export_table: 'billing_accounts'
    export_table_primary_key: id
    import_db: CUSTOMERS_DB
    import_query: |-
      SELECT id
      , zuora_account_name
      , zuora_account_id
      , salesforce_account_id
      , created_at
      , updated_at
      FROM billing_accounts
  billing_account_contacts:
    advanced_metadata: true
    export_db: EXPORT_DB
    export_schema: 'customers'
    export_table: 'billing_account_contacts'
    export_table_primary_key: id
    import_db: CUSTOMERS_DB
    import_query: |-
      SELECT id
      , work_email
      , created_at
      , updated_at
      , zuora_contact_id
      , zuora_account_id
      FROM billing_account_contacts
  billing_account_memberships:
    advanced_metadata: true
    export_db: EXPORT_DB
    export_schema: 'customers'
    export_table: 'billing_account_memberships'
    export_table_primary_key: id
    import_db: CUSTOMERS_DB
    import_query: |-
      SELECT id
      , customer_id
      , billing_account_id
      , created_at
      , updated_at
      FROM billing_account_memberships
