version: 2
models:
  - name: ws_finance_adaptive_accounts
    description: Adaptive account info
    columns:
      - name: id
        tests:
          - not_null
  - name: ws_finance_adaptive_attributes
    description: Adaptive attributes info
    columns:
      - name: parent_id
        tests:
          - not_null
  - name: ws_finance_adaptive_dimension_families
    description: Adaptive dimension family info
    columns:
      - name: id
        tests:
          - not_null
  - name: ws_finance_adaptive_dimension_mapping
    description: Adaptive dimension mapping info 
    columns:
      - name: version_id
        tests:
          - not_null
      - name: dimension_id
        tests:
          - not_null
  - name: ws_finance_adaptive_dimensions
    description: Adaptive dimension info 
    columns:
      - name: parent_id
        tests:
          - not_null
  - name: ws_finance_adaptive_instances
    description: Adaptive instance info 
    columns:
      - name: instance_name
        tests:
          - not_null
  - name: ws_finance_adaptive_users
    description: Adaptive users info
    columns:
      - name: id
        tests:
          - not_null
  - name: ws_finance_adaptive_versions
    description: Adaptive version info 
    columns:
      - name: parent_id
        tests:
          - not_null
