version: 2

models:
    - name: dbt_source_freshness
      description: 'The current status of all DBT sources along with when the sources were last loaded.'
      columns:
        - name: freshness_observed_at
          data_tests:
            - not_null
        - name: source_freshness_state
          data_tests:
            - not_null
        - name: table_name
          data_tests:
            - not_null
    - name: dbt_compilation_runtime
      description: 'The most recent not null compilation time elapsed for each DBT model.'
      columns:
        - name: model_name
          data_tests:
            - not_null
            - unique
        - name: compilation_time_seconds_elapsed
          data_tests:
            - not_null
    - name: dbt_failing_data_tests
      description: The DBT data_tests that are failing as of the last recorded test runs.
      columns:
        - name: test_unique_id
          data_tests:
            - not_null
            - unique
        - name: generated_at
          data_tests:
            - not_null            
    - name: dbt_last_successful_test_runs
      description: The timestamp of the last successful test run for data_tests that are currently failing.
      columns:
        - name: test_unique_id
          data_tests:
            - not_null
            - unique
            - relationships:
                to: ref('dbt_failing_data_tests')
                field: test_unique_id
        - name: last_successful_run_at
    - name: dbt_run_results
      description: "Information about compilation/execution time for DBT models."
    - name: dbt_snapshots_results
      description: Model for dbt snapshot results
    - name: dbt_source_data_tests
      description: Model for source testing
    - name: dbt_test_results
      description: "DBT test results by name and time"
