version: 2

models:
  - name: commonroom_activities_source
    description: '{{ doc("commonroom_activities_source") }}'
    columns:
      - name: activity_timestamp
        tests:
          - not_null
      - name: activity_type
        tests:
          - not_null
      - name: first_activity_date
      - name: full_name
        tests:
          - not_null
        meta:
          sensitive: true
      - name: member_token
        meta:
          sensitive: true
      - name: profiles
      - name: service_name
        tests:
          - not_null
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at") }}'
  - name: commonroom_community_members_source
    description: '{{ doc("commonroom_community_members_source") }}'
    columns:
      - name: first_activity_date
      - name: first_activity_source
      - name: full_name
        tests:
          - not_null
        meta:
          sensitive: true
      - name: impact_points_all_time
      - name: last_activity_date
      - name: location
        meta:
          sensitive: true
      - name: member_tokens
        meta:
          sensitive: true
      - name: primary_email
        meta:
          sensitive: true
      - name: profiles
      - name: segment_names
      - name: tags
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at") }}'
  - name: commonroom_organizations_source
    description: '{{ doc("commonroom_organizations_source") }}'
    columns:
      - name: approx_revenue_max
      - name: approx_revenue_min
      - name: domain
        tests:
          - not_null
      - name: employee_count
        tests:
          - not_null
      - name: first_seen_date
      - name: first_seen_source
      - name: last_seen_date
      - name: location
        meta:
          sensitive: true
      - name: member_count
      - name: organization_name
        tests:
          - not_null
      - name: _uploaded_at
        description: '{{ doc("_uploaded_at") }}'
