version: 2

sources:
  - name: sales_analytics
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: sales_analytics
    loader: JupyterNotebooks
    loaded_at_field: _uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: xray_curves_qtd_fitted
      - name: xray_curves_fy_n4q_fitted