version: 2

models:
  - name: sensitive_queries_source
    description: '{{ doc("sensitive_queries_source") }}'
    columns:
      - name: TBA
        data_tests:
          - not_null
          - unique