version: 2

models:
  - name: sensitive_queries_tags
    description: '{{ doc("sensitive_queries_tags") }}'
    columns:
      - name: classification_type,
      - name: tag_name,
      - name: tag_value,
      - name: accessed_database,
      - name: accessed_schema,
      - name: accessed_table,
      - name: accessed_column
  - name: sensitive_queries_source
    description: '{{ doc("sensitive_queries_source") }}'
  - name: sensitive_queries_details
    description: '{{ doc("sensitive_queries_details") }}'